import * as RA from 'ramda-adjunct';
import { expectType } from 'tsd';

expectType<boolean>(RA.isNaturalNumber(5));
expectType<boolean>(RA.isNaturalNumber(Number.MAX_VALUE));
expectType<boolean>(RA.isNaturalNumber(0));
expectType<boolean>(RA.isNaturalNumber(-1));
expectType<boolean>(RA.isNaturalNumber(0.9));
expectType<boolean>(RA.isNaturalNumber(+0));
expectType<boolean>(RA.isNaturalNumber(null));
expectType<boolean>(RA.isNaturalNumber(true));
expectType<boolean>(RA.isNaturalNumber(NaN));
expectType<boolean>(RA.isNaturalNumber({}));
expectType<boolean>(RA.isNaturalNumber([]));
expectType<boolean>(RA.isNaturalNumber(() => {}));
expectType<boolean>(RA.isNaturalNumber('string'));
expectType<boolean>(RA.isNaturalNumber(1));
expectType<boolean>(RA.isNaturalNumber(Object()));
expectType<boolean>(RA.isNaturalNumber(Object(5)));
expectType<boolean>(RA.isNaturalNumber(new Map()));
expectType<boolean>(RA.isNaturalNumber(new Set()));
